apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hitcounter-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  # backend:
  #   serviceName: default-http-backend
  #   servicePort: 80
  rules:
  # - host: localhost
  - http:
      paths:
      - path: /counter
        backend:
          serviceName: hitcounter-service
          servicePort: 8080
